# Generated by Django 5.1.2 on 2024-10-11 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_faq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainabout',
            name='subtitle',
        ),
        migrations.AddField(
            model_name='mainabout',
            name='descriptions',
            field=models.TextField(default=458, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='services',
            name='descriptions',
            field=models.TextField(max_length=200),
        ),
    ]
